# Generated by Django 4.1.2 on 2022-10-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videojuego',
            new_name='Juego',
        ),
    ]
